config/routes.rb
PhotoRama::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users
  resources :projects

  constraints(Subdomain) do
    match '/' => 'projects#show'
    get '/add_item_to_menu' => 'projects#add_item_to_menu'
    put '/change_style' => 'projects#change_style'
    get '/render_block_tpl' => 'projects#render_block_tpl'
    get '/render_block_control' => 'projects#render_block_control'
    put '/change_logo' => 'projects#change_logo', as: :change_logo

    constraints :page_id => /([a-z0-9\-\_]{3,})/ do
      get ":page_id" => "page_modules#show", as: :page_module
      scope ":page_id" do
        resources :albums do
          resources :photos
        end
      end
      resources :page_modules


      post 'page_modules/menu_update_order' => 'page_modules#menu_update_order', as: :menu_update
      post 'page_modules/delete_page' => 'page_modules#delete_page', as: :delete_page
      post 'page_modules/retrieve_page' => 'page_modules#retrieve_page', as: :retrieve_page
      post 'page_modules/update_page' => 'page_modules#update_page', as: :update_page

    end

    resources :static_pages
    resources :main_pages, only: [:update, :create]
  end
  root to: 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos
  belongs_to :gallery_attr
  attr_accessible :desc, :order, :title, :gallery_type
end

app/models/background.rb
class Background < ActiveRecord::Base
  attr_accessible :background, :name
  mount_uploader :background, BgUploader
  has_many :projects
end

app/models/color_scheme.rb
class ColorScheme < ActiveRecord::Base
  attr_accessible :color1, :color2, :color3, :color4, :color5, :color6, :color7, :name
  has_many :projects
end

app/models/gallery.rb
class Gallery < PageModule
  has_one :gallery_attr, dependent: :destroy
  has_many :albums
  #alias_attribute :attribute, :gallery_attr

  validate :gallery_creating_count, :on => :create

  def gallery_creating_count
    if self.project.page_modules.where(type: 'Gallery').count >= 1
      errors.add(:base, "Exceeded thing limit")
    end
  end
end

app/models/gallery_attr.rb
class GalleryAttr < ActiveRecord::Base
  belongs_to :gallery
  attr_accessible :gallery_id
  has_many :albums
end

app/models/main_page.rb
class MainPage < PageModule
  belongs_to :project
  has_one :main_page_attr, dependent: :destroy
end

app/models/main_page_attr.rb
class MainPageAttr < ActiveRecord::Base
  belongs_to :main_page
  attr_accessible :content, :gallery_toggle
end

app/models/main_slider.rb
class MainSlider < ActiveRecord::Base
  belongs_to :photo
  # attr_accessible :title, :body
end

app/models/page_module.rb
# encoding=utf-8
class PageModule < ActiveRecord::Base
  belongs_to :project
  attr_accessible :anchor, :slug, :type, :project_id, :deleted, :deleted_at, :order

  validates :slug, format: { with: /^[a-z0-9][a-z0-9\-]*[a-z0-9]$/,
                                  message: "в slug страницы не должно быть спец.символов" }
  validates :slug,
            presence: true,
            uniqueness: { scope: :project_id }

  validate :pages_count_limit, :on => :create

  def pages_count_limit
    if self.project.page_modules.count >= 5
      errors.add(:base, "Exceeded thing limit")
    end
  end

  validates :anchor,
            presence: true
  TYPES = [['Статическая страница', 'StaticPage'], ['Галлерея', 'Gallery']]

  scope :deleted_pages, -> { where(deleted:true) }
  scope :not_deleted_pages, -> { where(deleted:false) }
  scope :by_order, -> {order('"order"')}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file, PhotoUploader
  belongs_to :album
  attr_accessible :desc, :file, :title
end

app/models/project.rb
# encoding=utf-8
class Project < ActiveRecord::Base
  attr_accessible :subdomain, :title, :template_id, :color_scheme_id, :background_id, :logo
  belongs_to :user
  belongs_to :template
  belongs_to :color_scheme
  belongs_to :background
  mount_uploader :logo, LogoUploader

  has_many :page_modules

  validates :title, :subdomain, presence: true
  validates :title, :subdomain, length: { minimum: 2 }
  validates :subdomain, uniqueness: true
  validates :subdomain, format: { with: /^[a-z0-9][a-z0-9\-]*[a-z0-9]$/,
                                  message: "в названии субдомена не должно быть спец.символов" }
end

app/models/static_page.rb
class StaticPage < PageModule
  belongs_to :project
  has_one :static_page_attr, dependent: :destroy
end

app/models/static_page_attr.rb
class StaticPageAttr < ActiveRecord::Base
  belongs_to :static_page
  attr_accessible :content
end

app/models/template.rb
class Template < ActiveRecord::Base
  attr_accessible :name, :layout_name, :thumbnail
  mount_uploader :thumbnail, TemplateUploader
  has_many :projects
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :city, :telephone, :full_name
  # attr_accessible :title, :body
  has_one :project
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def link_to_fancy_photo(photo)
    link_to image_tag( photo.file.thumb.url, alt: photo.title, class: 'img-polaroid'),  photo.file.url, class: 'photos', rel: 'shadowbox[group]'
  end

  def link_to_galleriffic_photo(photo)
    link_to image_tag( photo.file.thumb.url, alt: photo.title, class: 'span2'),  photo.file.url, class: 'thumb', name: photo.id, title: photo.title
  end

end

app/helpers/url_helper.rb
module UrlHelper
  def with_subdomain(subdomain)
    subdomain = (subdomain || "")
    subdomain += "." unless subdomain.empty?
    [subdomain, request.domain].join
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title PhotoRama
    = stylesheet_link_tag    "application/application", :media => "all"
    = csrf_meta_tags
    = yield :head
  body
    .navbar
      .navbar-inner
        ul.nav.pull-right
          li
            a href='#'
              | Главная
          li
            a href='#'
              | Помощь
    = yield

app/views/layouts/default.html.slim
doctype html
html
  head
    title PhotoRama
    = stylesheet_link_tag    "default/default", :media => "all"
    = javascript_include_tag "default/default"
    = yield :head
    -if @templates
      = stylesheet_link_tag    "control_panel", :media => "all"
      = javascript_include_tag "control_panel"
    = csrf_meta_tags
  body
    -if @templates
      = render partial: 'partial/control_panel'
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="/"
            span.color-highlight Photo
            | grapher
          .nav-collapse
            ul.nav.pull-right
              = render partial: 'partial/menu'
    .container
      hr
      .row
        .span12
          .well
            = yield
      hr
      footer.row
        p
          | ©2012 Your Company.
          br
            | Сайт сделан при помощи сервиса
            a href="#"
              |ФОТОРАМА

app/views/layouts/gray_red.html.slim
doctype html
html
  head
    title PhotoRama
    = stylesheet_link_tag    "gray_red/gray_red", :media => "all"
    = javascript_include_tag "gray_red/gray_red"
    = yield :head
    -if @templates
      = stylesheet_link_tag    "control_panel", :media => "all"
      = javascript_include_tag "control_panel"
    = csrf_meta_tags
    / javascript:
    /   jQuery(window).load(function() {
    /   $x = $(window).width();
    /   if($x > 1024)
    /   jQuery('.magnifier').touchTouch();
    /   });
  body
    -if @templates
      = render partial: 'partial/control_panel'
    /! ============================== header =================================
    header
      .container.clearfix
        .row
          .span12
            .navbar.navbar_
              .container
                h1.brand.brand_
                  a href="index.html"
                    = image_tag "gray_red/logo.gif"
                  a.btn.btn-navbar.btn-navbar_ data-target=".nav-collapse_" data-toggle="collapse"
                  | Menu
                  span.icon-bar
                .nav-collapse.nav-collapse_.collapse
                  ul.nav.sf-menu
                    = render partial: 'partial/menu'
    .bg-content
      #content.content-extra
        .container
          .row
            article.span12
              = yield
    /! ============================== footer =================================
    footer
      .container.clearfix
        ul.list-social.pull-right
          li
            a.icon-1 href="#"
          li
            a.icon-2 href="#"
          li
            a.icon-3 href="https://twitter.com/oswt"
          li
            a.icon-4 href="#"
        .privacy.pull-left
          |© Сайт сделан при помощи сервиса ФОТОРАМА.

app/views/layouts/project.html.slim
doctype html
html
  head
    title PhotoRama
    = stylesheet_link_tag    "project/manifest", :media => "all"
    = javascript_include_tag "project/manifest"
    = yield :head
    -if @templates
      = stylesheet_link_tag    "control_panel", :media => "all"
      = javascript_include_tag "control_panel"
    = csrf_meta_tags
    = render partial: 'partial/red/color_scheme'
  body.bg_color1
    header.bg_color3
      .container
        .row
          .span12
            h1 = current_user
    nav.bg_color2
      .container
        .row
          .span12
            ul#menu.nav.nav-pills
              = render partial: 'partial/menu'
    /section#carousel.bg_color3
      h3 ololo
      / Nothing
    section#main-content.bg_color3
      .container
        = yield
    footer.bg_color1
      .container
        .row
          .span6
            p © Сайт сделан при помощи сервиса ФОТОРАМА.
          .span6.text-right
            p Ваша правовая информация здесь

app/views/layouts/red.html.slim
doctype html
html
  head
    title PhotoRama
    = stylesheet_link_tag    "red/red", :media => "all"
    = javascript_include_tag "red/red"
    = yield :head
    -if @templates
      = stylesheet_link_tag    "control_panel", :media => "all"
      = javascript_include_tag "control_panel"
    = csrf_meta_tags
    = render partial: 'partial/red/color_scheme'
  body.bg_color1
    -if @templates
      = render partial: 'partial/control_panel'
    .header.bg_color3.border_color1
      .wrap
        .navbar.navbar_.clearfix
          .container
            .row
              .span4
                .logo
                  a href="index.html"
                    - if @project.logo
                      = image_tag @project.logo
                    - else
                      = image_tag 'red/logo.png'
              .span8
                .clear
                nav#main_menu
                  .menu_wrap
                    ul#menu.nav
                      = render partial: 'partial/menu'
    .page_container.bg_color3
      .breadcrumb.bg_color2
        .wrap
          .container
            | Главная / Какая-то страница
      .wrap.main_content
        .container
          = yield
    #footer
      .footer_bottom.bg_color1
        .wrap
          .container
            .row
              .span5
                .foot_logo
                  a href="index.html"
                    = image_tag 'red/foot_logo.png'
              .span7
                .foot_right_block
                  .foot_menu
                    ul
                      li
                        a href="index.php"
                          = t(:main_page)

                  .copyright © Сайт сделан при помощи сервиса ФОТОРАМА.

app/views/partial/_control_panel.html.slim
.control-panel
  #dialog_box
  .container
    .row
      .span12.control_hide_block
        .tabbable.tabs-left
          ul.nav.nav-tabs
            li.active
              a href="#design" data-toggle="tab"
                | Дизайн
            li
              a href="#page_control" data-toggle="tab"
                | Управление страницами
            li
              a href="#logo_upload" data-toggle="tab"
                | Логотип

          .tab-content
            .tab-pane.active#design
              = render partial: 'partial/control_panel/design'
            .tab-pane#page_control
              .row
                = render partial: 'partial/control_panel/showed_page'
                = render partial: 'partial/control_panel/deleted_page'
                .span4
                  .update_form
            .tab-pane#logo_upload
              = render partial: 'partial/control_panel/logo_upload'
  .hide_pointer
    .container
      .row
        .span6
        .span2
          =link_to content_tag(:i, '', class: 'icon-home icon-white position-fix')+'PhotoRama', root_url(subdomain: false)
        .span2
          a.profile
            i.icon-user.icon-white.position-fix
            |Настройки профиля
        .span2
          a.slide-show.text-right
            i.icon-arrow-up.icon-white
            |Панель управления

app/views/partial/_enter_form.html.slim
= form_for :user, :url => new_user_session_path, :html => {:class => 'form-horizontal'} do |form|
    fieldset
      legend
        span Вход

      div.control-group
        = form.label :email, 'Электронная почта', :class => 'control-label'
        div.controls
          = form.text_field :email

      div.control-group
        = form.label :password, 'Пароль', :class => 'control-label'
        div.controls
          = form.password_field :password

      div.control-group
        div.controls
          = form.label :remember_me, :class => 'checkbox'  do
              span Запомнить меня
              = form.check_box :remember_me

      div.control-group
        div.controls
          = form.submit 'Войти', :class => 'btn btn-success'

app/views/partial/_logged_user_links.html.slim
|Привет, 
- if current_user.full_name
  = current_user.full_name
- else
  = current_user.email
|!
br
= link_to "Перейти к управлению свои сайтом!", root_url(:host => with_subdomain(current_user.project.subdomain))

app/views/partial/_menu.html.slim
- @menu.not_deleted_pages.each do |menu|
  - if menu.slug == 'main'
    = content_tag(:li, content_tag(:i, '',class: ('icon-move menu-move' if @templates)) + link_to(menu.anchor, root_url(host: with_subdomain(@project.subdomain))), id: "menu_#{menu.id}", class: 'sortable_item')
  - else
    = content_tag(:li, content_tag(:i, '',class: ('icon-move menu-move' if @templates)) + link_to(menu.anchor, page_module_url(page_id: menu.slug, host: with_subdomain(@project.subdomain))), id: "menu_#{menu.id}", class: 'sortable_item')
- if @templates
  li.add_item_to_menu
    span
      i.icon-plus
      | &nbsp;Добавить страницу

app/views/partial/_photos_gallery_fancybox2.html.slim
- photos.each do |photo|
  .span3
    h3
      = photo.title
    = link_to_fancy_photo photo

- content_for :head do

  = javascript_include_tag 'plugins/shadowbox'
  = stylesheet_link_tag    'plugins/shadowbox/shadowbox', :media => 'all'

  javascript:
    Shadowbox.init();

app/views/partial/_photos_gallery_galerffies.html.slim
#gallery.content
  #controls.controls
  .slideshow-container
    #loading.loader
    #slideshow.slideshow
  #caption.caption-container
#thumbs.navigation.span5
  ul.thumbs.noscript
    - photos.each do |photo|
      li
        = link_to_galleriffic_photo photo
        .caption
          .image-title
            = photo.title
          .image-desc
            = photo.desc

- content_for :head do
  = javascript_include_tag 'plugins/galleriffic/galleriffic'
  = stylesheet_link_tag    'plugins/galleriffic/galleriffic', :media => 'all'

  javascript:
    jQuery(document).ready(function($) {
      // We only want these styles applied when javascript is enabled
      $('div.navigation').css({'float' : 'left'});
      $('div.content').css('display', 'block');

      // Initially set opacity on thumbs and add
      // additional styling for hover effect on thumbs
      var onMouseOutOpacity = 0.67;
      $('#thumbs ul.thumbs li').opacityrollover({
        mouseOutOpacity:   onMouseOutOpacity,
        mouseOverOpacity:  1.0,
        fadeSpeed:         'fast',
        exemptionSelector: '.selected'
      });

      // Initialize Advanced Galleriffic Gallery
      var gallery = $('#thumbs').galleriffic({
        delay:                     2500,
        numThumbs:                 "#{photos.count}",
        preloadAhead:              10,
        enableTopPager:            true,
        enableBottomPager:         true,
        maxPagesToShow:            10,
        imageContainerSel:         '#slideshow',
        controlsContainerSel:      '#controls',
        captionContainerSel:       '#caption',
        loadingContainerSel:       '#loading',
        renderSSControls:          true,
        renderNavControls:         true,
        playLinkText:              'Play Slideshow',
        pauseLinkText:             'Pause Slideshow',
        prevLinkText:              '&lsaquo; Previous Photo',
        nextLinkText:              'Next Photo &rsaquo;',
        nextPageLinkText:          'Next &rsaquo;',
        prevPageLinkText:          '&lsaquo; Prev',
        enableHistory:             false,
        autoStart:                 false,
        syncTransitions:           true,
        defaultTransitionDuration: 900,
        onSlideChange:             function(prevIndex, nextIndex) {
          // 'this' refers to the gallery, which is an extension of $('#thumbs')
          this.find('ul.thumbs').children()
            .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
            .eq(nextIndex).fadeTo('fast', 1.0);
        },
        onPageTransitionOut:       function(callback) {
          this.fadeTo('fast', 0.0, callback);
        },
        onPageTransitionIn:        function() {
          this.fadeTo('fast', 1.0);
        }
      });
    });

app/views/partial/_photos_gallery_galleriffic.html.slim
#gallery.content
  #controls.controls
  .slideshow-container
    #loading.loader
    #slideshow.slideshow
  #caption.caption-container
#thumbs.navigation.span5
  ul.thumbs.noscript
    - photos.each do |photo|
      li
        = link_to_galleriffic_photo photo
        .caption
          .image-title
            = photo.title
          .image-desc
            = photo.desc

- content_for :head do
  = javascript_include_tag 'plugins/galleriffic/galleriffic'
  = stylesheet_link_tag    'plugins/galleriffic/galleriffic', :media => 'all'

  javascript:
    jQuery(document).ready(function($) {
      // We only want these styles applied when javascript is enabled
      $('div.navigation').css({'float' : 'left'});
      $('div.content').css('display', 'block');

      // Initially set opacity on thumbs and add
      // additional styling for hover effect on thumbs
      var onMouseOutOpacity = 0.67;
      $('#thumbs ul.thumbs li').opacityrollover({
        mouseOutOpacity:   onMouseOutOpacity,
        mouseOverOpacity:  1.0,
        fadeSpeed:         'fast',
        exemptionSelector: '.selected'
      });

      // Initialize Advanced Galleriffic Gallery
      var gallery = $('#thumbs').galleriffic({
        delay:                     2500,
        numThumbs:                 "#{photos.count}",
        preloadAhead:              10,
        enableTopPager:            true,
        enableBottomPager:         true,
        maxPagesToShow:            10,
        imageContainerSel:         '#slideshow',
        controlsContainerSel:      '#controls',
        captionContainerSel:       '#caption',
        loadingContainerSel:       '#loading',
        renderSSControls:          true,
        renderNavControls:         true,
        playLinkText:              'Play Slideshow',
        pauseLinkText:             'Pause Slideshow',
        prevLinkText:              '&lsaquo; Previous Photo',
        nextLinkText:              'Next Photo &rsaquo;',
        nextPageLinkText:          'Next &rsaquo;',
        prevPageLinkText:          '&lsaquo; Prev',
        enableHistory:             false,
        autoStart:                 false,
        syncTransitions:           true,
        defaultTransitionDuration: 900,
        onSlideChange:             function(prevIndex, nextIndex) {
          // 'this' refers to the gallery, which is an extension of $('#thumbs')
          this.find('ul.thumbs').children()
            .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
            .eq(nextIndex).fadeTo('fast', 1.0);
        },
        onPageTransitionOut:       function(callback) {
          this.fadeTo('fast', 0.0, callback);
        },
        onPageTransitionIn:        function() {
          this.fadeTo('fast', 1.0);
        }
      });
    });

app/views/partial/_photos_gallery_shadowbox.html.slim
- photos.each do |photo|
  .span3
    h3
      = photo.title
    = link_to_fancy_photo photo

- content_for :head do

  = javascript_include_tag 'plugins/shadowbox/shadowbox'
  = stylesheet_link_tag    'plugins/shadowbox/shadowbox', :media => 'all'

  javascript:
    Shadowbox.init();

app/views/partial/_register_form.html.slim
= form_for :user, :url => user_registration_path, :html => {:class => 'form-horizontal'} do |form|
    fieldset
      legend
        span Регистрация

      div.control-group
        = form.label :email, 'Электронная почта', :class => 'control-label'
        div.controls
          = form.text_field :email

      div.control-group
        = form.label :password, 'Пароль', :class => 'control-label'
        div.controls
          = form.password_field :password

      div.control-group
        = form.label :password_confirmation, 'Пароль еще раз', :class => 'control-label'
        div.controls
          = form.password_field :password_confirmation

      div.control-group
        div.controls
          = form.submit 'Зарегистрироваться', :class => "btn btn-primary"

app/views/partial/blocks/_block.html.slim
- number_of_columns = @number_of_columns.to_i
- span_value = 12/number_of_columns
.row.block-wrap
  .span12
    = render partial: 'partial/blocks/block_control'
    .row.block-content
      - until number_of_columns.zero? do
        - number_of_columns -= 1
        div.ololo(class="span#{span_value}")
          .block-editable-area

app/views/partial/blocks/_block_control.html.slim
.row.block-control
  .span12
    .btn-group
      = link_to '#', {class: 'merge-block btn', title: 'Объединить колонки'} do
        i.icon-resize-small
      = link_to '#', {class: 'split-block btn', title: 'Разделить колонку'} do
        i.icon-resize-full
      = link_to '#', {class: 'remove-block btn', title: 'Удалить эту строку'} do
        i.icon-remove

app/views/partial/blocks/_blocks_control_panel.html.slim
.row.add-block-panel
  .span12
    .btn-toolbar
      .btn-group
        = link_to 'I', '#', {class: 'add_block_to_main_content btn', title: 'Добавить одну колонку', 'data-number-of-columns' => 1}
        = link_to 'II', '#', {class: 'add_block_to_main_content btn', title: 'Добавить две колонки', 'data-number-of-columns' => 2}
        = link_to 'III', '#', {class: 'add_block_to_main_content btn', title: 'Добавить три колонки', 'data-number-of-columns' => 3}
        = link_to 'IIII', '#', {class: 'add_block_to_main_content btn', title: 'Добавить четыре колонки', 'data-number-of-columns' => 4}
      .btn-group
        = link_to '#', {class: 'block-sortable btn', title: 'Изменить порядок блоков'} do
          i.icon-move
      .btn-group
        = link_to 'Сохранить', '#', {class: 'block-page-save btn', title: 'Сохранить страницу', 'data-page-id' => @module.id }

app/views/partial/control_panel/control/_add_item_to_menu_form.html.slim
= simple_form_for :page_modules, url: page_modules_path do |add_module|
  = add_module.text_field :anchor
  = add_module.text_field :slug
  = add_module.input :module_type, collection: PageModule::TYPES
  = add_module.submit

app/views/partial/control_panel/control/_edit_item_to_menu_form.html.slim
|Изменение параметров страницы
= simple_form_for :page_modules, url: update_page_path, html: {id: 'update_module_page'} do |add_module|
  = add_module.input :id, as: :hidden, input_html: { value: @page_params.id}
  = add_module.input :anchor, input_html: { value: @page_params.anchor}
  -unless @page_params.slug == 'main'
    = add_module.input :slug, input_html: { value: @page_params.slug}
  = add_module.submit 'Update page', id: 'submit_page_update'

app/views/partial/control_panel/design/_background.html.slim
button.prev_bg Влево
button.next_bg Вправо
div
    ul#background_list.select_to_list(data-target="#project_background_id")
      - if @project.background_id == nil
        - class_name = "active"
      li(data-value="0" class=class_name)
        div
          | Не использовать
      - @backgrounds.each do |item|
        - class_name = nil
        - if @project.background_id == item.id
          - class_name = "active"
        li(data-value="#{item.id}" class=class_name)
          div(style="background-image: url('#{item.background}');")

app/views/partial/control_panel/design/_color_lines.html.slim
button.prev_color Влево
button.next_color Вправо
div
    ul#color_list.select_to_list(data-target="#project_color_scheme_id")
      - @color_schemes.each do |item|
        - if @project.color_scheme_id == item.id
          - class_name = "active"

        li(data-value="#{item.id}" class=class_name )
          div(style="background-color: #{item.color1};")
          div(style="background-color: #{item.color2};")
          div(style="background-color: #{item.color3};")
          div(style="background-color: #{item.color4};")
          div(style="background-color: #{item.color5};")

app/views/partial/control_panel/design/_templates.html.slim
button.prev_tpl Влево
button.next_tpl Вправо
div
    ul#templates_list.select_to_list(data-target="#project_template_id")
      - @templates.each do |item|
        - if @project.template_id == item.id
          li.active(data-value="#{item.id}")
            img(src="#{item.thumbnail.thumb}" width="160px" height="100px")
        - else
          li(data-value="#{item.id}")
            img(src="#{item.thumbnail.thumb}" width="160px" height="100px")

app/views/partial/red/_color_scheme.html.erb
<style>
<%- if @project.color_scheme %>
<%-  colors = @project.color_scheme %>
<%- else %>
<%-  colors = ColorScheme.first %>
<%- end %>

.bg_color1 {
  background-color: <%= colors.color1 %>;
  color: <%= colors.color7 %>;
}
.bg_color1 a {
  color: <%= colors.color6 %>;
}
.bg_color1 a:hover {
  color: <%= colors.color3 %>;
}

.bg_color2 {
  background-color: <%= colors.color2 %>;
  color: <%= colors.color3 %>;
}
.bg_color2 a {
    color: <%= colors.color3 %>;
}
.bg_color2 a:hover {
    color: <%= colors.color1 %>;
    background-color: <%= colors.color4 %> !important;
}

.bg_color3 {
  background-color: <%= colors.color3 %>;
  color: <%= colors.color6 %>;
  border-color: <%= colors.color1 %>;
}
.bg_color3 h1, .bg_color3 h2, .bg_color3 h3, .bg_color3 h4, .bg_color3 h5, .bg_color3 h6, .bg_color3 a {
  color: <%= colors.color1 %> !important;
}
.bg_color3 a:hover {
  color: <%= colors.color4 %> !important;
}

.bg_color4 {
  background-color: <%= colors.color4 %>;
}

.bg_color5 {
  background-color: <%= colors.color5 %>;
}

<%- if @project.background %>
.bg_color3 {
    background-image: url('<%= @project.background.background %>');
}
<%- end %>
</style>