config/routes.rb
PhotoRama::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users
  resources :projects

  constraints(Subdomain) do
    match '/' => 'projects#show'
    get '/add_item_to_menu' => 'projects#add_item_to_menu'
    put '/change_style' => 'projects#change_style'
    get '/render_block_tpl' => 'projects#render_block_tpl'
    get '/render_block_control' => 'projects#render_block_control'
    put '/change_logo' => 'projects#change_logo', as: :change_logo

    constraints :page_id => /([a-z0-9\-\_]{3,})/ do
      get ":page_id" => "page_modules#show", as: :page_module
      scope ":page_id" do
        resources :albums do
          resources :photos
        end
      end
      resources :page_modules


      post 'page_modules/menu_update_order' => 'page_modules#menu_update_order', as: :menu_update
      post 'page_modules/delete_page' => 'page_modules#delete_page', as: :delete_page
      post 'page_modules/retrieve_page' => 'page_modules#retrieve_page', as: :retrieve_page
      post 'page_modules/update_page' => 'page_modules#update_page', as: :update_page

    end

    resources :static_pages
    resources :main_pages, only: [:update, :create]
  end
  root to: 'welcome#index'

end

app/models/project.rb
# encoding=utf-8
class Project < ActiveRecord::Base
  attr_accessible :subdomain, :title, :template_id, :color_scheme_id, :background_id, :logo
  belongs_to :user
  belongs_to :template
  belongs_to :color_scheme
  belongs_to :background
  mount_uploader :logo, LogoUploader

  has_many :page_modules

  validates :title, :subdomain, presence: true
  validates :title, :subdomain, length: { minimum: 2 }
  validates :subdomain, uniqueness: true
  validates :subdomain, format: { with: /^[a-z0-9][a-z0-9\-]*[a-z0-9]$/,
                                  message: "в названии субдомена не должно быть спец.символов" }
end

app/controllers/projects_controller.rb
# encoding=utf-8
class ProjectsController < ApplicationController

  before_filter :authenticate_user!, :except => :show
  before_filter :template_variables_load, only: :show
  layout :load_template

  def show
      @module = @project.page_modules.find_by_slug(params[:page_id])
      @page = MainPageAttr.find_by_main_page_id(@module.id)
      render template: 'page_modules/main_page.html.slim'
  end

  def new
    if current_user.project
      redirect_to root_url(:host => with_subdomain(current_user.project.subdomain))
    else
      render :layout => 'application'
    end
  end

  def create
    @project = current_user.build_project(params[:project])
    @project.save
    @mainpage = MainPage.new(slug: 'main', anchor: 'Главная', project_id: @project.id)
    @mainpage.save
    redirect_to root_url(:host => with_subdomain(@project.subdomain))
  end

  def change_style
    @project = Project.where(subdomain:request.subdomain).first
    @project.update_attributes(params[:project])
    if @project.save
      redirect_to root_url(:host => with_subdomain(@project.subdomain))
    end
  end

  def add_item_to_menu
    render partial: 'partial/control_panel/control/add_item_to_menu_form'
  end

  def change_logo
    @project = Project.find_by_subdomain(request.subdomain)
    @project.update_attributes(logo: params[:project][:logo])
    if @project.save
      redirect_to root_url(:host => with_subdomain(@project.subdomain))
    end
  end

  def render_block_tpl
    @number_of_columns = params[:columns]
    render partial: 'partial/blocks/block'
  end

  def render_block_control
    render partial: 'partial/blocks/block_control'
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def link_to_fancy_photo(photo)
    link_to image_tag( photo.file.thumb.url, alt: photo.title, class: 'img-polaroid'),  photo.file.url, class: 'photos', rel: 'shadowbox[group]'
  end

  def link_to_galleriffic_photo(photo)
    link_to image_tag( photo.file.thumb.url, alt: photo.title, class: 'span2'),  photo.file.url, class: 'thumb', name: photo.id, title: photo.title
  end

end

app/views/projects/new.html.slim
- content_for :head do
  = javascript_include_tag 'jquery'
  = javascript_include_tag 'plugins/urlify'
  javascript:
    jQuery(function($){
      $(document).on('keyup', '#project_title', function() {
        $('#project_subdomain').val(URLify($(this).val()))
        $('.help-inline').fadeIn()
      })
    })
.container
  .row
    .span12
      legend =t(:project_new)
      = form_for(:project, url: projects_path, html: { class: 'form-horizontal' }) do |f|
        .control-group
          = f.label :title, t(:project_title), class: 'control-label'
          .controls
            = f.text_field :title
        .control-group
          = f.label :subdomain, t(:project_subdomain),  class: 'control-label'
          .controls
            = f.text_field :subdomain
            span.help-inline.hide Вы можете изменить адрес
        .control-group
          .controls
            = f.submit 'Создать'

app/views/projects/show.html.slim
- if @page.nil?
  h1 Добро пожаловать!
  p
    | Это первая страничка вашего сайта, вы можете начать создавать новые странички. Добавить модули на сайт, и наполнить сайт своим содержимым.