config/routes.rb
PhotoRama::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users
  resources :projects

  constraints(Subdomain) do
    match '/' => 'projects#show'
    get '/add_item_to_menu' => 'projects#add_item_to_menu'
    put '/change_style' => 'projects#change_style'
    get '/render_block_tpl' => 'projects#render_block_tpl'
    get '/render_block_control' => 'projects#render_block_control'
    put '/change_logo' => 'projects#change_logo', as: :change_logo

    constraints :page_id => /([a-z0-9\-\_]{3,})/ do
      get ":page_id" => "page_modules#show", as: :page_module
      scope ":page_id" do
        resources :albums do
          resources :photos
        end
      end
      resources :page_modules


      post 'page_modules/menu_update_order' => 'page_modules#menu_update_order', as: :menu_update
      post 'page_modules/delete_page' => 'page_modules#delete_page', as: :delete_page
      post 'page_modules/retrieve_page' => 'page_modules#retrieve_page', as: :retrieve_page
      post 'page_modules/update_page' => 'page_modules#update_page', as: :update_page

    end

    resources :static_pages
    resources :main_pages, only: [:update, :create]
  end
  root to: 'welcome#index'

end

app/models/page_module.rb
# encoding=utf-8
class PageModule < ActiveRecord::Base
  belongs_to :project
  attr_accessible :anchor, :slug, :type, :project_id, :deleted, :deleted_at, :order

  validates :slug, format: { with: /^[a-z0-9][a-z0-9\-]*[a-z0-9]$/,
                                  message: "в slug страницы не должно быть спец.символов" }
  validates :slug,
            presence: true,
            uniqueness: { scope: :project_id }

  validate :pages_count_limit, :on => :create

  def pages_count_limit
    if self.project.page_modules.count >= 5
      errors.add(:base, "Exceeded thing limit")
    end
  end

  validates :anchor,
            presence: true
  TYPES = [['Статическая страница', 'StaticPage'], ['Галлерея', 'Gallery']]

  scope :deleted_pages, -> { where(deleted:true) }
  scope :not_deleted_pages, -> { where(deleted:false) }
  scope :by_order, -> {order('"order"')}
end

app/controllers/page_modules_controller.rb
class PageModulesController < ApplicationController
  before_filter :authenticate_user!, except: :show
  before_filter :template_variables_load, only: :show
  layout :load_template
  respond_to :js, only: [:menu_update_order, :delete_page, :retrieve_page, :update_page]

  def create
    new_page = params[:page_modules][:module_type].constantize.new(slug: params[:page_modules][:slug], anchor: params[:page_modules][:anchor], project_id: current_user.project.id)

    if new_page.save
      if params[:page_modules][:module_type] == 'Gallery'
        GalleryAttr.create(:gallery_id => Gallery.last.id)
      end
      redirect_to page_module_url(page_id: new_page.slug, host: with_subdomain(current_user.project.subdomain))
    else
      flash[:error] = t(:new_page_not_created)
      redirect_to root_url(host: with_subdomain(current_user.project.subdomain))
    end
  end

  def delete_page
    delete_page = PageModule.find(params[:page_modules][:id])
    if delete_page.slug == 'main'
      flash[:error] = t(:main_page_do_not_delet)
    else
      unless delete_page.update_attributes(deleted: true, deleted_at: Time.now)
        flash[:error] = t(:page_not_deleted)
      end
    end
  end

  def retrieve_page
    unless PageModule.find(params[:page_modules][:id]).update_attributes(deleted: false)
      flash[:error] = t(:page_not_retrieved)
    end
  end

  def update_page
    PageModule.find(params[:page_modules][:id]).update_attributes(params[:page_modules].delete_if{|key, value| value.blank? })
  end

  def menu_update_order
    unless PageModule.update(params[:menu_order].keys, params[:menu_order].values)
      flash[:error] = t(:page_order_not_updated)
    end
  end

  def edit
    @page_params = PageModule.find(params[:id])
    render partial: 'partial/control_panel/control/edit_item_to_menu_form'
  end

  def show
    @module = @project.page_modules.find_by_slug(params[:page_id])
    @page = (@module.type + 'Attr').constantize
    @page = @page.where((@module.type.underscore + '_id').to_sym => @module.id).first
    render 'page_modules/' + @module.type.underscore + '.html.slim'
  end
end

app/views/page_modules/delete_page.js.erb
<% if flash[:error] %>
  $('body').prepend('<% flash[:error] %>');
<% end %>
$('#deleted_pages, #visible_pages').removeClass('menu_update');
$('#deleted_pages, #visible_pages').sortable('enable');

app/views/page_modules/gallery.html.slim
- if @page
  div.page-content.tgl-block
    - if @templates
      = link_to 'Add Album', new_album_path(@module.slug)
  ul
  - @page.albums.each do |album|
    li
      = link_to album.title,  album_path(id:album.id, page_id:@module.slug)

app/views/page_modules/main_page.html.slim
/- if @page
/  div.page-content.tgl-block
/    - if @templates
/      div.edit-icon
/        i.icon-pencil
/    = raw @page.content
/  - if @templates
/    div.redactor-block.tgl-block
/      = form_for @page, url: main_page_path(@page), method: :put do |form|
/        = form.text_area :content, class: 'redactor'
/        = form.hidden_field :main_page_id
/        = form.submit
/        = form.button t(:cancel), class: 'cancel-redactor'
/- else
/  div.page-content.tgl-block
/    - if @templates
/      div.edit-icon
/        i.icon-pencil
/    - fish_text = "Вы ещё не заполнили главную страничку. но вы всегда это можете сделать!"
/    p =fish_text
/  - if @templates
/    div.redactor-block.tgl-block
/      = form_for :main_page_attr, url: main_pages_path do |form|
/        = form.check_box :gallery_toggle
/        = form.label :on_gallery
/        = form.text_area :content, class: 'redactor', value: fish_text
/        = form.hidden_field :main_page_id, value: @module.id
/        = form.submit
/        = form.button t(:cancel), class: 'cancel-redactor'

app/views/page_modules/menu_update.js.erb
<% if flash[:error] %>
  $('body').prepend('<% flash[:error] %>');
<% end %>
$('#menu').removeClass('menu_update');
$('#menu').sortable('enable');

app/views/page_modules/menu_update_order.js.erb
<% if flash[:error] %>
  $('body').prepend('<% flash[:error] %>');
<% end %>
$('#menu').removeClass('menu_update');
$('#menu').sortable('enable');

app/views/page_modules/retrieve_page.js.erb
<% if flash[:error] %>
  $('body').prepend('<% flash[:error] %>');
<% end %>
$('#deleted_pages, #visible_pages').removeClass('menu_update');
$('#deleted_pages, #visible_pages').sortable('enable');

app/views/page_modules/static_page.html.slim
- if @project_owner
  = render partial: 'partial/blocks/blocks_control_panel'
.row.page-head
  .span12
    h1 =@module.anchor
- if @page
  /.row.block-wrap
    .span12
      /= render partial: 'partial/blocks/block_control'
      .row.block-content
        .span12
          .block-editable-area
            = @page.content.html_safe
  = @page.content.html_safe
- else
  .row.block-wrap
    .span12
      /= render partial: 'partial/blocks/block_control'
      .row.block-content
        .span12
          .block-editable-area
            | Это созданная вами страничка "#{@module.anchor}" Вы можете начать изменять её, просто кликнув по этому тексту. Вашему вниманию откроется редактор, в котором вы сможете ввести свой текст, добавить картинки на страницу, и сделать её такой какой хотите видеть сами.

app/views/page_modules/update_page.js.erb
$('.update_form').html('');
$('#elem_<%= params[:page_modules][:id] %>').html('<i class="icon-move menu-move"></i><%= params[:page_modules][:anchor] %> <span class="edit_page">edit</span>');